drug_form_groups = {
    "Drug Implant Product": ["Drug Implant", "Intrauterine System"],
    "Inhalant & Nasal Product": [
        "Dry Powder Inhaler",
        "Gas for Inhalation",
        "Inhalation Powder",
        "Inhalation Solution",
        "Inhalation Spray",
        "Inhalation Suspension",
        "Metered Dose Inhaler",
        "Metered Dose Nasal Spray",
        "Nasal Inhalant",
        "Nasal Spray",
        "Nasal Gel",
        "Nasal Ointment",
        "Nasal Powder",
        "Nasal Solution",
        "Powder for Nasal Solution",
    ],
    "Injectable Product": [
        "Auto-Injector",
        "Cartridge",
        "Injectable Foam",
        "Injectable Solution",
        "Injectable Suspension",
        "Injection",
        "Jet Injector",
        "Pen Injector",
        "Prefilled Syringe",
    ],
    "Intraperitoneal Product": ["Intraperitoneal Solution"],
    "Intratracheal Product": ["Intratracheal Suspension"],
    "Irrigation Product": ["Irrigation Solution"],
    "Mucosal Product": ["Mucosal Spray", "Mucous Membrane Topical Solution"],
    "Ophthalmic Product": [
        "Drug-Eluting Contact Lens",
        "Ophthalmic Cream",
        "Ophthalmic Gel",
        "Ophthalmic Irrigation Solution",
        "Ophthalmic Ointment",
        "Ophthalmic Solution",
        "Ophthalmic Spray",
        "Ophthalmic Suspension",
    ],
    "Oral Product": [
        "Buccal Film",
        "Buccal Tablet",
        "Chewable Extended Release Oral Tablet",
        "Chewable Tablet",
        "Chewing Gum",
        "Delayed Release Oral Capsule",
        "Delayed Release Oral Granules",
        "Delayed Release Oral Tablet",
        "Disintegrating Oral Tablet",
        "Effervescent Oral Tablet",
        "Extended Release Oral Capsule",
        "Extended Release Oral Tablet",
        "Extended Release Suspension",
        "Granules for Oral Solution",
        "Granules for Oral Suspension",
        "Mouthwash",
        "Oral Capsule",
        "Oral Cream",
        "Oral Film",
        "Oral Flakes",
        "Oral Foam",
        "Oral Gel",
        "Oral Granules",
        "Oral Lozenge",
        "Oral Ointment",
        "Oral Paste",
        "Oral Pellet",
        "Oral Powder",
        "Oral Solution",
        "Oral Spray",
        "Oral Suspension",
        "Oral Tablet",
        "Oral Wafer",
        "Powder for Oral Solution",
        "Powder for Oral Suspension",
        "Sublingual Film",
        "Sublingual Powder",
        "Sublingual Tablet",
        "Sustained Release Buccal Tablet",
        "Tablet for Oral Suspension",
        "Toothpaste",
    ],
    "Otic Product": ["Otic Gel", "Otic Ointment", "Otic Solution", "Otic Suspension"],
    "Pyelocalyceal Product": ["Powder for Pyelocalyceal Solution"],
    "Rectal Product": [
        "Enema",
        "Rectal Cream",
        "Rectal Foam",
        "Rectal Gel",
        "Rectal Ointment",
        "Rectal Solution",
        "Rectal Spray",
        "Rectal Suppository",
    ],
    "Shampoo Product": ["Medicated Shampoo"],
    "Soap Product": ["Medicated Bar Soap", "Medicated Liquid Soap"],
    "Topical Product": [
        "Medicated Pad",
        "Medicated Patch",
        "Medicated Tape",
        "Powder Spray",
        "Topical Cream",
        "Topical Foam",
        "Topical Gel",
        "Topical Liquefied Gas",
        "Topical Lotion",
        "Topical Oil",
        "Topical Ointment",
        "Topical Powder",
        "Topical Solution",
        "Topical Spray",
        "Topical Suspension",
        "Transdermal System",
    ],
    "Urethral Product": ["Urethral Suppository"],
    "Vaginal Product": [
        "Douche",
        "Vaginal Cream",
        "Vaginal Film",
        "Vaginal Foam",
        "Vaginal Gel",
        "Vaginal Insert",
        "Vaginal Ointment",
        "Vaginal Sponge",
        "Vaginal System",
    ],
}
